sonar.projectKey=intelliParkMobile
sonar.projectName=intelliParkMobile
sonar.projectVersion=1.0
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.spec.ts
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/app/lcov.info
sonar.host.url=http://localhost:9000
sonar.token=sqp_ba07ee59dec36566d62f92b8d52886654f8dd8c3